win_width: 750
win_height: 750

floor_color: [0., 0.47058823529411764, 0]
n_bloques: 3
n_bonus: 0

n_tortuga: 2
n_tortuga_humanoide: 2
n_ninjas: 2
n_pope_ninjas: 1

enemy_tortuga_speed: 5
enemy_tortuga_humanoide_speed: 2
enemy_ninja_speed: 4
enemy_pope_ninja_speed: 6

enemy_tortuga_bombs:  0
enemy_tortuga_humanoide_bombs: 1
enemy_ninja_bombs: 1
enemy_pope_ninja_bombs: 4

bots_can_bomb : 0

bomber_initial_speed: 5
bomber_initial_pose: [1,1]
bomber_initial_bombs: 1